{% set version = "3.9-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rseis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RSEIS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RSEIS/RSEIS_{{ version }}.tar.gz
  sha256: bc70e1db530294b25c830ecfe91de9da94a8d95d566bee43c864d4cd88d337f3

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rpmg
    - r-rwave
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rpmg
    - r-rwave

test:
  commands:
    - $R -e "library('RSEIS')"           # [not win]
    - "\"%R%\" -e \"library('RSEIS')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RSEIS
  license: GPL-2.0-or-later
  summary: Multiple interactive codes to view and analyze seismic data, via spectrum analysis, wavelet transforms, particle motion, hodograms.  Includes general time-series tools, plotting, filtering, interactive display.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RSEIS
# Type: Package
# Title: Seismic Time Series Analysis Tools
# Version: 3.9-0
# Date: 2019-09-15
# Depends: R (>= 3.0)
# Imports: RPMG, Rwave
# Suggests: stats
# Authors@R: c(person(given="Jonathan M.", family="Lees", role = c("aut", "cre"),email = "jonathan.lees@unc.edu"), person(given="Jake", family="Anderson", role = "ctb", email = "ajakef@gmail.com"), person(given='Leonard', family='Lisapaly', role = "ctb", email = "leonardl@fisika.ui.ac.id"), person(given='Dave', family='Harris', role=c('aut', 'cph') ) )
# Author: Jonathan M. Lees [aut, cre], Jake Anderson [ctb], Leonard Lisapaly [ctb], Dave Harris [aut, cph]
# Maintainer: Jonathan M. Lees <jonathan.lees@unc.edu>
# Description: Multiple interactive codes to view and analyze seismic data, via spectrum analysis, wavelet transforms, particle motion, hodograms.  Includes general time-series tools, plotting, filtering, interactive display.
# License: GPL (>= 2)
# Copyright: see inst/COPYRIGHTS
# Packaged: 2019-09-18 17:39:37 UTC; lees
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2019-09-18 19:20:05 UTC
