travis:
  secure:
    BINSTAR_TOKEN: RYF1Yo8gSQem6geq6LQs/elTDoYBR8EUKPniQb86hrEEPiErfLZfqY/yltqFBBrxzJiK4W5+JCZjmcl7didyyKAiojMU06Nh+25zM1wEoClnBg3htpIwqBe19Z8riApY1Wb60tHIGU2sDvYuBy2dv6UJwy0ODYYJ8PPd6/OiIcwiUOkDJB6f2J6QQBCxwIPzXkPLhDyWCFamhSiGECKJL4jJyjJaLn6u+gvc5cVwSUFkOnQV+fFsngZFNvhMMLkcSzLQc2d4tQBFcR5GD39FLesFG3RpyPJ6jvV9dMddFsnMdWpyXxprJ8ONV6zw3oRo2yHnBJ6w1kI5t9gdDM0PiA1Wj4GNNaUX4uUQzhEuEokCirtxh5Nyt9gAViFRYlAlcIC2fdR+5hLP6ymUAR7xbRZ+KF/Oplup3xuvEoU1gDBUw00nhTwxEtbVWVxXU1Qm7HneML/wCYVZ3l+exW7718CluAlZemerk3uF9sp+tBOBiRZPc94+ro+Tgjj8drGd7vrNz8Bi7623IysuXlDlEGz/ho6r/jK7R8LG0UiTpZ5NLhl6B493uJ/nahDJwAeLNvEVDtXyFSKX5R5woHS93s7gYGqPbFCjejlng3RIs3MV7olgLS7pY18wN300vp7Xe1EKEY/QlTkeLi5Kgf/FLu4H+qFxDmW1eZJ+vfrrlio=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
